from __future__ import print_function
import scipy.misc
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split

# The data, split between train and test sets:
data1=np.load('/home/Bear/attack_detection/cw_cnn_cifar10/cw2_con0/cw2_con0_5_1208/X.npy')
data2=np.load('/home/Bear/attack_detection/cw_resnet_cifar10/cifar10_all/5/X.npy')
data3=np.load('/home/Bear/attack_detection/cw_vgg16_cifar10/cifar10_all/5/X.npy')
data4=np.load('/home/Bear/attack_detection/cw_vgg19_cifar10/cifar10_all/5/X.npy')
data5=np.load('/home/Bear/attack_detection/deepfool_cnn_cifar10/cifar10_all/5/X.npy')
data6=np.load('/home/Bear/attack_detection/deepfool_resnet_cifar10/cifar10_all/5/X.npy')
data7=np.load('/home/Bear/attack_detection/deepfool_vgg16_cifar10/cifar10_all/5/X.npy')
data8=np.load('/home/Bear/attack_detection/deepfool_vgg19_cifar10/cifar10_all/5/X.npy')
data9=np.load('/home/Bear/attack_detection/fgsm_cnn_cifar10/cifar10_all/5/X.npy')
data10=np.load('/home/Bear/attack_detection/fgsm_resnet_cifar10/cifar10_all/05/X.npy')
data11=np.load('/home/Bear/attack_detection/fgsm_vgg16_cifar10/cifar10_all/5/X.npy')
data12=np.load('/home/Bear/attack_detection/fgsm_vgg19_cifar10/cifar10_all/5/X.npy')

label1=np.load('/home/Bear/attack_detection/cw_cnn_cifar10/cw2_con0/cw2_con0_5_1208/Y.npy')
label2=np.load('/home/Bear/attack_detection/cw_resnet_cifar10/cifar10_all/5/Y.npy')
label3=np.load('/home/Bear/attack_detection/cw_vgg16_cifar10/cifar10_all/5/Y.npy')
label4=np.load('/home/Bear/attack_detection/cw_vgg19_cifar10/cifar10_all/5/Y.npy')
label5=np.load('/home/Bear/attack_detection/deepfool_cnn_cifar10/cifar10_all/5/Y.npy')
label6=np.load('/home/Bear/attack_detection/deepfool_resnet_cifar10/cifar10_all/5/Y.npy')
label7=np.load('/home/Bear/attack_detection/deepfool_vgg16_cifar10/cifar10_all/5/Y.npy')
label8=np.load('/home/Bear/attack_detection/deepfool_vgg19_cifar10/cifar10_all/5/Y.npy')
label9=np.load('/home/Bear/attack_detection/fgsm_cnn_cifar10/cifar10_all/5/Y.npy')
label10=np.load('/home/Bear/attack_detection/fgsm_resnet_cifar10/cifar10_all/05/Y.npy')
label11=np.load('/home/Bear/attack_detection/fgsm_vgg16_cifar10/cifar10_all/5/Y.npy')
label12=np.load('/home/Bear/attack_detection/fgsm_vgg19_cifar10/cifar10_all/5/Y.npy')
print(data1.shape)
print(data2.shape)
print(data3.shape)
print(data4.shape)
print(data5.shape)
print(data6.shape)
print(data7.shape)
print(data8.shape)
print(data9.shape)
print(data10.shape)
print(data11.shape)
print(data12.shape)

X_all=np.concatenate((data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12),axis=0)
Y_all=np.concatenate((label1,label2,label3,label4,label5,label6,label7,label8,label9,label10,label11,label12),axis=0)
print(X_all.shape)
print(Y_all.shape)
# print(np.max(x_test-x_adtest[0]))
x_train, x_test, y_train, y_test = train_test_split(X_all, Y_all, test_size=0.3)

np.save('/home/Bear/attack_detection/a good detector/X_all', X_all)
np.save('/home/Bear/attack_detection/a good detector/ Y_all', Y_all)
np.save('/home/Bear/attack_detection/a good detector/y_train_all', y_train)
np.save('/home/Bear/attack_detection/a good detector/y_test_all', y_test)
np.save('/home/Bear/attack_detection/a good detector/x_train_all', x_train)
np.save('/home/Bear/attack_detection/a good detector/x_test_all', x_test)
np.save('/home/Bear/attack_detection/a good detector/y_train_all', y_train)
np.save('/home/Bear/attack_detection/a good detector/y_test_all', y_test)
